routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Http\Controllers\questionformController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

Route::get('/', function () {
    return view('table.table');
});

Route::get('/data-tables', function() {
    return view('table.tbData');
});

// Route::get('/question/form-question','questionformController@tampilform');
// Route::post('/question','questionformController@store');
// Route::get('/question','questionformController@tampil');
// Route::get('/question/{id}/edit', 'questionformController@edit');
// Route::get('/question/{id}', 'questionformController@detail');
// Route::put('/question/{id}', 'questionformController@update');
// Route::delete('/question/{id}', 'questionformController@destroy');

//pertanyaan
Route::resource('question', 'questionformController');

//jawaban
Route::get('/jawaban/{id}', 'jawabanController@create');
Route::post('/jawaban/{id}', 'jawabanController@store');
Route::get('/jawaban/{jawaban}/edit', 'jawabanController@edit');
Route::put('/jawaban/{pertanyaan}/{jawaban}', 'jawabanController@update');
Route::delete('/jawaban/{id}', 'jawabanController@destroy');

//komentar pertanyaan
Route::get('/komentar-question/{id}', 'quesKomController@create');
Route::post('/komentar-question/{id}', 'quesKomController@store');
Route::get('/komentar-question/{id}/show', 'quesKomController@show');
Route::get('/komentar-question/{id}/edit', 'quesKomController@edit');
Route::put('/komentar-question/{pertanyaan}/{komentar}', 'quesKomController@update');
Route::delete('/komentar-question/{id}','quesKomController@destroy');
Auth::routes();

//like
Route::get('/like/{id}', 'questionformController@like');

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/register','HomeController@formurl');
Route::post('/welcome', 'AuthController@welcome');

resources/views/form/editQuestion.blade.php
@extends('template.master');

@push('style')
  <!-- Theme style -->
  <link rel="stylesheet" href="{{asset('adminlte/dist/css/adminlte.min.css')}}">
  <!-- summernote -->
  <link rel="stylesheet" href="{{asset('adminlte/plugins/summernote/summernote-bs4.css')}}">
@endpush

@section('content')
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
          <h1>Edit Post {{$data->judul}}</h1>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-sm-2"></div>
        <div class="col-md-8">
          <div class="card card-outline card-info">
            <div class="card-header">

            <form role="form" action="{{route('question.update', ['question', $data->id ])}}" method="POST">
                @csrf
                @method('PUT')
                <div class="card-body">
                  <div class="form-group">
                    <label for="judul">Judul Pertanyaan</label>
                  <input type="text" class="form-control" id="judul" name="judul" value="{{old('judul',$data->judul)}}" placeholder="Masukkan Judul Pertanyaan" required>
                    @error('judul')

                        <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                  </div>
                  <div class="form-group">
                    <label for="isi">Pertanyaan Anda :</label>
                    <textarea class="textarea" placeholder="Place some text here"
                          style="width: 100%; height: 200px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;" id="isi" name="isi"  required>{{old('isi',$data->isi)}}</textarea>
                    @error('isi')

                        <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                    <p class="text-sm mb-0">
                            Editor <a href="https://github.com/summernote/summernote">Documentation and license
                            information.</a>
                    </p>
                  </div>
                <div class="card-footer">
                  <button type="submit" class="btn btn-primary" style="width: 100%">Submit</button>
                </div>
              </form>
            </div>
          </div>
        </div>
        <!-- /.col-->
      </div>
      <!-- ./row -->
    </section>
@endsection

@push('script')
    <!-- Summernote -->
<script src="{{asset('adminlte/plugins/summernote/summernote-bs4.min.js')}}"></script>
<script>
  $(function () {
    // Summernote
    $('.textarea').summernote()
  })
</script>
@endpush

resources/views/form/questionForm.blade.php
@extends('template.master');

@push('style')
  <!-- Theme style -->
  <link rel="stylesheet" href="{{asset('adminlte/dist/css/adminlte.min.css')}}">
  <!-- summernote -->
  <link rel="stylesheet" href="{{asset('adminlte/plugins/summernote/summernote-bs4.css')}}">
@endpush

@section('content')
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Form Pertanyaan</h1>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-md-12">
          <div class="card card-outline card-info">
            <div class="card-header">

            <form role="form" action="{{route('question.store')}}" method="POST">
                @csrf
                <div class="card-body">
                  <div class="form-group">
                    <label for="judul">Judul Pertanyaan</label>
                  <input type="text" class="form-control" id="judul" name="judul" value="{{old('judul','')}}" placeholder="Masukkan Judul Pertanyaan" required>
                    @error('judul')

                        <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                  </div>
                  <div class="form-group">
                    <label for="isi">Pertanyaan Anda :</label>
                    <textarea class="textarea" placeholder="Place some text here"
                          style="width: 100%; height: 200px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;" id="isi" name="isi"  required>{{old('isi','')}}</textarea>
                    @error('isi')

                        <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                    <p class="text-sm mb-0">
                            Editor <a href="https://github.com/summernote/summernote">Documentation and license
                            information.</a>
                    </p>
                  </div>
                <div class="card-footer">
                  <button type="submit" class="btn btn-primary" style="width: 100%">Submit</button>
                </div>
              </form>
            </div>
          </div>
        </div>
        <!-- /.col-->
      </div>
      <!-- ./row -->
    </section>
@endsection

@push('script')
    <!-- Summernote -->
<script src="{{asset('adminlte/plugins/summernote/summernote-bs4.min.js')}}"></script>
<script>
  $(function () {
    // Summernote
    $('.textarea').summernote()
  })
</script>
@endpush